language: ruby
cache: bundler
script:
- bundle exec rake
- _utility/publish.sh
env:
  global:
  - secure: O1PqxDrrVH8Nw4+D15MfjVjlKideU+PPjaHb8zuqr4Uo3SovjwDvPiZMsw3sS9kXQrevldl+ax/qlCsQEo3esWRfpNzjC4MKtDkPMiaAgYD/6+VNfqOE/daQVMOl6VN9LXxa0cyIYoqAwe3RLUT6+P4RWFNOj52HfeO7ssnk+Ikr3dGQML7UEh+P936sOmvFpbVw33nT72R+ep3qTmQ9owucUDYI9awm0xEzjMROqhsVqkCl4X3c4s84hlFRL1l1Q5ah96fJYRjrKDHymQlQJ2hflvU1aI5sTo0IJJ50DHA2Rn/5NCXG7OFDUWM7nXce+Ecy7QU73B94Tuuf7tHtG4sOSZxhRH91iShdpH1DN8RhBTGvjtNOlfbH8QLPuFCI5+lv8oZwbT7vm2q6kH3/EqW3evKa+zXcDhJ2Nc/Qs+tLTm+3jmrGzAaLVZlDAotI5p4RYbB+Lxyhykmqxlc941JfEGxJRsVR0RmD3x3LWbsU0vKYxf0BUi6/9D7GCTMIKMrORZlr6We/eBaISskgIi9KiclO7BD0qLUjczNxR4+zg4z7e56jH08b3748X6dG1Mpi5PAMUb4JAWmVetI2NJYGGV4gBiaC1jLO6iBIQYAscIN+ChLo2OTcxabSt1kvd9geK2AboeeHxc9hYRp6i/jZqyo5G6fg38d0jhaLif4=
