language: ruby
cache: bundler
script:
- bundle exec rake
- _utility/publish.sh
env:
  global:
    secure: C6mP2HfAul0WavqhpMcLYTpZYOnrKnaXx9zYBNOIZwi5/ZoBRNPKPjpttc9UbM9EBmTZCjtuQTZ21lzjlwMIfjvN9u88SweYq4MuQbOehSF65bDH3r2V/H3xEZV3GIjo90T/pgAf9ZkoEKmjJjlb2cBMLhMYWV7RSeMHxF0vBgxSg1yW7N37qUv90KW3q4QMRu+GV3tCibK6wp37zNYDrntV/rhHoJu2hT03Yh/jTvz/MTknVynZ2JRSF30e/NAMge4qv4Jv3tOqUXy27SJEBDF0bfMqxyGuWTxSQVeIWupzVv4JGi2WzxggG0kA/Jh+S7iqQ3EPmPwx6e8W8F0QYi+SYySVHws/Ghdd/tcX0792irz3WG5EZ8vgd2CLk9QLlLaBvdFKNNP6vSoxudQSOTrFxrYmPLmaa0EXfg8eMS4CnwvOx4M5wOukRUpxHOMJ5a0IszjSDNyq7q1PYn4/Lpxy97SGGxQiTTN4QNn3RHxz9x3MbKMAAaG++DvaVKz9E3P5AwcsAqQeBDy51hTNzoFSJoOJcve10Ox65y2YEfqXKEaCa7LvegtxxMr9yEnqonqYH5w9WxdvLLqBqUpnkzOKgRvSA35Be6aKwyVsv30zpYMiWWef0kw+qoYU3IkC9DfOFqbJvyAMYR9ZJccuxpLIzFqDyz0Hxi0dS+1kS4U=
