language: ruby
cache: bundler
script:
- bundle exec rake
- _utility/publish.sh
env:
  global:
    secure: h3Kw8ZuCGJh9QyQMoyivjTzLa43Kby40ycZkjNEfNRqrwXbfyPLMHbty3RiZ/NvYm25BvHMi30EMiqz/EnN0IQYK9APIqOZ/aGSQxgTzQEwMa5qyEr804YvdEHwyhPpxtlDWSOcjaaRuK3ENXqjPwCAGUDtQ6/oXAOyOM9bsg9A=
