language: ruby
cache: bundler
script:
- bundle exec rake
- _utility/publish.sh
env:
  global:
    secure: Y2eezA/sKLghxIfN13Aj3vZCwZsIklOApQfKGZeKstCL4knLSOxbROB9H4rDFJOPv0Z9RD7A6hsY+kcrv53LlyliHiuXlTGipyAZlxYa6v3JU27H2ga/E5JLu/KYvXoR5J64BOtjJwZ27t2rPxmOFrp+lnSCI79V9br69Wm3RAviNfiy3Vquw23xWPibmLEq7jSTV7Odz1Pt+c4++iGJzNF00ZWVSOzvLDFD4O912tFWVKHvaFE5bCa8v1FqtqvOXbcRqlWvb1g77zqQ3AZ4r50p+f3Q2hFT9P+G9y6K1TqCxjFl4sxcACrFoW+UPFvE/er1p7Nr9C+dFMhUwQCcA5PPairurKVjNg+D4e47Jx2MWLABzrqExXhVZrT20hhlnDQie9oYE1kQIZkSJyAmM5cXOPTjrDo3IqaDZC9JemcPhfIGT/hiwPwPQMkjYPRyxDy/vlOc+ibGFYVNT8CbxD788hM5tZ4RkPy46YqgtW2CtrRujPZWgrg5eRiXISF3VZHDhWG2VLMYJ4+Re9ksKR7QAXvpo1kVeA9hx6euVEIBqL44GQ3FbxJl7uDHHywnnkdgY872yxjqEWnTi1VEVpYzGm6Y+OZ/uR7btZopV3Uy8EU4ghYSCRPQAqvUkhNN5PINtRYFuQwNwQ30/VOdieB+0Ef9rUvl6gwRW760zfk=
