url: "http://codurance.com"
highlighter: rouge 
permalink: pretty
markdown: rdiscount
rdiscount:
  extensions:
    - footnotes     # footnotes

exclude: ["README.md", "_posts_TOFIX", "vendor"]

author_dir: pubications/author

tag_page_layout: tag_page
tag_page_dir: publications/tag
tag_page_layout: tag

paginate: 10
paginate_path: "/publications/page:num"

sitename: "Codurance"
subtitle: "craft at heart"
email: "hello@codurance.com"

googleanalytics:
  account: UA-46289079-1

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
