url: "http://codurance.com"
highlighter: pygments
permalink: pretty
markdown: rdiscount
rdiscount:
  extensions:
    - footnotes     # footnotes

exclude: ["README.md", "_posts_TOFIX", "vendor"]

author_dir: blog/author

tag_page_layout: tag_page
tag_page_dir: blog/tag
tag_page_layout: tag

paginate: 10
paginate_path: "/blog/page:num"

sitename: "Codurance"
subtitle: "craft at heart"
email: "hello@codurance.com"

googleanalytics:
  account: UA-46289079-1
