url: "http://codurance.com"
pygments: true
permalink: /blog/:year/:month/:title/
markdown: rdiscount

exclude: ["README.md", "_posts_TOFIX"]

paginate: 10
paginate_path: "blog/page:num"

sitename: "Codurance"
subtitle: "craft at heart"
email: "hello@codurance.com"